### ISSUE TITLE
[ecbuff] possible to accidentally read newest (overwritten) element with ECB_WRITE_OVERWRITE ?

### ISSUE THREAD

**Issue by fenugrec** [EliasOenal/etools#2]
Hi,
looking at 
https://github.com/EliasOenal/etools/blob/c3e3bb4c7f0f086c766c93114a2a1a4ae98a79b2/ecbuff.c#L175

Isn't there a window of time between setting 'rb->wp = wp;' and incrementing rp (to drop the oldest element) , where it would be possible for the consumer to accidentally read the element that was just pushed in ?

**Comment by EliasOenal** [comment]
Yes, but this is by design. ecbuff_cfg.h warns about it: `ECB_WRITE_OVERWRITE ***WARNING: Not thread-safe!*** Only supported when ECB_THREAD_SINGLE is defined.`
I don't know if there is a good way to make this thread safe, but I am open for ideas.

**Comment by fenugrec** [comment]
Ah, I missed that comment about not being thread-safe.
OVERWRITE behaviour isn't something I need, but maybe something like this would work ? [EDIT : no, see below]

- before MEMCPY  in _write(), check if there would be an overwrite
- increment rp, dropping the last element
- MEMCPY
- update wp

One minor weakness is the writer may be dropping elements a bit more often than theoretically necessary, if it's often operating near max capacity. E.g. the consumer thread reads an element after "check if there will be an overwrite" but before the writer's MEMCPY : in principle there would be no need to overwrite but the writer increment's rp anyway, dropping an extra element.

**Comment by EliasOenal** [comment]
I believe this will cause race conditions. The reader may still be (slowly) reading an element while the writer invalidates the element and overwrites the data. For non-atomic elements the reader may now read a corrupt element as it gets overwritten.

**Comment by fenugrec** [comment]
You're correct, I hadn't considered that.

**Comment by fenugrec** [comment]
Closing since the original issue was already documented, and there is no simple, obvious solution.
