### ISSUE TITLE
suggestion: modify asserts to allow external assert() definition

### ISSUE THREAD

**Issue by fenugrec** [EliasOenal/etools#4]
Using ecbuff as-is, if I #define ECB_ASSERT then it will use standard C assert() from <assert.h>.  This is a problem on small-memory embedded devices : assert() will often be implemented as a `fprintf(..__FILE__ , __LINE__ ...` ). (I don't want to include fprintf and all those strings !)

It would improve flexibility if for example: 
- ecbuff.c is modified to replace `assert(` with maybe  `ASSERT(`
- in ecbuff_cfg.h , provide a place to #define ASSERT ;
- in ecbuff.c, if ASSERT is undefined, then fallback to the current behaviour (#include <assert.h> etc if ECB_ASSERT is defined ), and then  `#define ASSERT(X) assert(X))`

What do you think ?
I could make a PR if interested.

**Comment by EliasOenal** [comment]
That's a good suggestion, I'll be happy to merge it! 👍
